### ISSUE TITLE
yNy doesn't work?

### ISSUE THREAD

**Issue by Sigafoos** [svermeulen/vim-easyclip#59]
Similar to #6: I confirmed that 3yy will work, but y3y does not. m3m doesn't work either, but d3d does.

I'll probably just try to train myself to use Nyy, since I have to relearn some keys anyway, but thought I should point it out.

**Comment by svermeulen** [comment]
Thanks for reporting this, I was not aware of it.

**Comment by svermeulen** [comment]
I spent some time thinking about this.

The best way I can think to address this is just this:

    onoremap m _
    onoremap y _

This will allow you to do `y3y` and `m3m` BUT it will also allow you to do `y3m` and `m3y` with the same effect, which is not the case in vanilla vim.  I think vim must do some special handling of these cases to allow this kind of thing, because technically it kind of violates the pattern of `[action][movement]` that's used everywhere else

I'd like to remain as compatible with vanilla vim as possible but I'm not sure I want to make this choice for the user, since they may want to map 'm' and 'y' to different movements other than the current line.  So I think I'll just mention it in the docs for anyone interested in this workaround.
